<?php

namespace Cryonighter\FormulaDoctrine\DBAL;

use Cryonighter\FormulaDoctrine\Metadata\FormulaRegistry;
use Doctrine\DBAL\Driver;
use Doctrine\DBAL\Driver\Middleware;

/**
 * DBAL Middleware that resolves #[Formula] fields in SQL generated by
 * BasicEntityPersister (find, findBy, findAll, lazy proxy initialization).
 *
 * FormulaSqlWalker handles DQL queries. This middleware handles all other
 * SQL paths where the Walker does not run.
 *
 * BasicEntityPersister always uses "t0" as the root entity table alias.
 * We detect formula column references like "t0.orderCount" and replace them
 * with the resolved SQL expression "(SELECT ... WHERE ... = t0.id)".
 */
final readonly class FormulaMiddleware implements Middleware
{
    public function __construct(
        private FormulaRegistry $registry,
    ) {}

    public function wrap(Driver $driver): Driver
    {
        return new FormulaDriver($driver, $this->registry);
    }
}
