<?php

namespace Cryonighter\FormulaDoctrine\DBAL;

use Cryonighter\FormulaDoctrine\Metadata\FormulaMetadata;
use Cryonighter\FormulaDoctrine\Metadata\FormulaMetadataRegistry;
use Doctrine\DBAL\Driver\Connection;
use Doctrine\DBAL\Driver\Middleware\AbstractConnectionMiddleware;
use Doctrine\DBAL\Driver\Result;
use Doctrine\DBAL\Driver\Statement;

/**
 * Intercepts SQL statements before execution and replaces formula column
 * references with their subquery expressions.
 *
 * Handles both root entity (t0) and eagerly joined entities (t1, t2, t4, etc.)
 * generated by BasicEntityPersister.
 *
 * @internal
 */
final class FormulaConnection extends AbstractConnectionMiddleware
{
    public function __construct(
        Connection $connection,
        private readonly FormulaMetadataRegistry $registry,
    ) {
        parent::__construct($connection);
    }

    public function prepare(string $sql): Statement
    {
        return parent::prepare($this->process($sql));
    }

    public function query(string $sql): Result
    {
        return parent::query($this->process($sql));
    }

    public function exec(string $sql): int
    {
        return parent::exec($this->process($sql));
    }

    private function process(string $sql): string
    {
        // Fast path: only process SELECT statements from BasicEntityPersister.
        // BasicEntityPersister always generates aliases like t0, t1, t4 etc.
        if (!str_starts_with(ltrim($sql), 'SELECT')) {
            return $sql;
        }

        $formulaAliases = $this->getFormulaAliases();

        if (!$formulaAliases) {
            return $sql;
        }

        $tableAliases = $this->extractTableAliases($sql);

        foreach ($tableAliases as $alias) {
            foreach ($formulaAliases as $columnAlias => $meta) {
                $columnRef = "$alias.$columnAlias";

                if (!str_contains($sql, $columnRef)) {
                    continue;
                }

                $resolvedSql = str_replace('{this}', $alias, $meta->sql);
                $sql = str_replace($columnRef, $resolvedSql, $sql);
            }
        }

        return $sql;
    }

    /**
     * Extracts all table aliases from the SQL statement.
     *
     * BasicEntityPersister generates aliases like t0, t1, t2, t4 etc.
     * Pattern matches: "FROM table_name tN" and "JOIN table_name tN"
     *
     * @return array<string>
     */
    private function extractTableAliases(string $sql): array
    {
        // Matches: FROM/JOIN <table_name> <alias>
        // Alias pattern: t followed by one or more digits (t0, t1, t4, t10...)
        preg_match_all('/(?:FROM|JOIN)\s+\w+\s+(t\d+)/i', $sql, $matches);

        return array_unique($matches[1] ?? []);
    }

    /**
     * Collects all formula metadata from all scanned classes,
     * indexed by column alias.
     *
     * @return array<string, FormulaMetadata>
     */
    private function getFormulaAliases(): array
    {
        $result = [];

        foreach ($this->registry->getScannedClasses() as $className) {
            foreach ($this->registry->getForClass($className) as $meta) {
                $result[$meta->alias] = $meta;
            }
        }

        return $result;
    }
}
