<?php

namespace Cryonighter\FormulaDoctrine\DBAL;

use Cryonighter\FormulaDoctrine\Metadata\FormulaMetadata;
use Cryonighter\FormulaDoctrine\Metadata\FormulaMetadataRegistry;
use Doctrine\DBAL\Driver\Connection;
use Doctrine\DBAL\Driver\Middleware\AbstractConnectionMiddleware;
use Doctrine\DBAL\Driver\Result;
use Doctrine\DBAL\Driver\Statement;
use RuntimeException;

/**
 * Intercepts SQL statements before execution and replaces formula column
 * references with their subquery expressions.
 *
 * Handles both root entity (t0) and eagerly joined entities (t1, t2, t4, etc.)
 * generated by BasicEntityPersister.
 *
 * @internal
 */
final class FormulaConnection extends AbstractConnectionMiddleware
{
    public function __construct(
        Connection $connection,
        private readonly FormulaMetadataRegistry $registry,
    ) {
        parent::__construct($connection);
    }

    public function prepare(string $sql): Statement
    {
        return parent::prepare($this->process($sql));
    }

    public function query(string $sql): Result
    {
        return parent::query($this->process($sql));
    }

    public function exec(string $sql): int
    {
        return parent::exec($this->process($sql));
    }

    private function process(string $sql): string
    {
        $command = strtoupper(substr(ltrim($sql), 0, strpos(ltrim($sql), ' ')));

        // Fast path: only process SELECT statements from BasicEntityPersister.
        // BasicEntityPersister always generates aliases like t0, t1, t4 etc.
        if (!in_array($command, ['SELECT', 'WITH', 'INSERT', 'UPDATE', 'DELETE'])) {
            return $sql;
        }

        $tableAliases = $this->extractTableAliases($sql);

        if (!$tableAliases) {
            return $sql;
        }

        $formulaAliases = $this->getFormulaAliases();

        if (!$formulaAliases) {
            return $sql;
        }

        foreach ($tableAliases as ['table' => $tableName, 'alias' => $tableAlias]) {
            foreach ($formulaAliases[$tableName] ?? [] as $columnAlias => $meta) {
                $columnName = $tableAlias ? "$tableAlias.$columnAlias" : $columnAlias;

                $countColumnName = substr_count($sql, $columnName);

                if (!$countColumnName) {
                    continue;
                }

                $formulaSql = str_replace('{this}', $tableAlias, $meta->sql);

                if ($countColumnName === 1 || !in_array($command, ['SELECT', 'WITH'])) {
                    $sql = str_replace($columnName, $formulaSql, $sql);

                    continue;
                }

                $columnNameEscaped = preg_quote($columnName);
                $regExp = "/$columnNameEscaped\s+(AS|as)\s+(\w+)([\s,])/";
                preg_match($regExp, $sql, $matches);

                if (empty($matches)) {
                    $sql = str_replace($columnName, $formulaSql, $sql);

                    continue;
                }

                $columnAlias = $matches[2];

                $sql = preg_replace($regExp, "$formulaSql AS {$columnAlias}{$matches[3]}", $sql, 1);
                $sql = str_replace($columnName, $columnAlias, $sql);

                // When using the #Formula and #Column attributes simultaneously, the field is somehow duplicated in the query
                // However, we remove metadata created via #Column if the field contains the #Formula attribute
                // I suspect that the find() mechanisms read the attribute contents directly, not the metadata
                // In any case, I decided not to investigate the cause of this behavior and simply removed the duplicates
                $sql = preg_replace("/$columnAlias\s+(AS|as)\s+$columnAlias([\s,])/", '', $sql);
            }
        }

        return $sql;
    }

    /**
     * Extracts all table aliases from the SQL statement.
     *
     * Matches: FROM/JOIN/INSERT INTO/UPDATE/DELETE FROM <table_name> [AS] [alias]
     * Context keywords: FROM, JOIN (all variants), INTO, UPDATE, DELETE
     * Table name: word characters
     * Optional alias:
     *    - explicit: AS <alias>
     *    - implicit: next token exists AND is not a SQL keyword
     *    - absent:   next token is a SQL keyword or end of string
     *
     * @return array<array<string, string>>
     */
    private function extractTableAliases(string $sql): array
    {
        // SQL keywords that can appear right after a table name when there is NO alias
        $sqlKeywords = [
            'SET', 'WHERE', 'ON', 'INNER', 'LEFT', 'RIGHT', 'FULL', 'CROSS',
            'OUTER', 'JOIN', 'FROM', 'INTO', 'UPDATE', 'DELETE', 'INSERT',
            'ORDER', 'GROUP', 'HAVING', 'LIMIT', 'OFFSET', 'UNION', 'EXCEPT',
            'INTERSECT', 'WITH', 'VALUES', 'SELECT',
        ];

        $pattern = '/
        (?:FROM|(?:INNER|LEFT|RIGHT|FULL|CROSS)\s+(?:OUTER\s+)?JOIN|JOIN|INTO|UPDATE|(?:DELETE\s+FROM))
        \s+
        (\w+)               # table name
        (?:
            \s+AS\s+(\w+)   # explicit alias: AS alias
            |
            \s+(?!(?:' . implode('|', $sqlKeywords) . ')\b)(\w+)  # implicit alias: not a keyword
        )?
    /xi';

        preg_match_all($pattern, $sql, $matches, PREG_SET_ORDER);

        if (empty($matches)) {
            return [];
        }

        $result = [];

        foreach ($matches as $match) {
            $table = $match[1];

            // Group 2 = explicit AS alias, Group 3 = implicit alias
            $alias = !empty($match[2]) ? $match[2] : (!empty($match[3]) ? $match[3] : null);

            $result[] = ['table' => $table, 'alias' => $alias];
        }

        return $result;
    }

    /**
     * Collects all formula metadata from all scanned classes,
     * indexed by table name and column alias.
     *
     * @return array<string, array<string, FormulaMetadata>>
     */
    private function getFormulaAliases(): array
    {
        $result = [];

        foreach ($this->registry->getMetadata() as $className => $formulas) {
            $tableName = $this->registry->getTableNameForClass($className);

            if (!$tableName) {
                throw new RuntimeException(sprintf('Table name not found for class "%s".', $className));
            }

            // Different classes can be bound to the same table, for example with #[ORM\InheritanceType('SINGLE_TABLE')]
            if (!isset($result[$tableName])) {
                $result[$tableName] = [];
            }

            foreach ($formulas as $meta) {
                $result[$tableName][$meta->alias] = $meta;
            }
        }

        return $result;
    }
}
