<?php

namespace Cryonighter\FormulaDoctrine\DBAL;

use Cryonighter\FormulaDoctrine\Mapping\FormulaMetadata;
use Cryonighter\FormulaDoctrine\Metadata\FormulaRegistry;
use Doctrine\DBAL\Driver\Connection;
use Doctrine\DBAL\Driver\Middleware\AbstractConnectionMiddleware;
use Doctrine\DBAL\Driver\Result;
use Doctrine\DBAL\Driver\Statement;

/**
 * Intercepts SQL statements before execution and replaces formula column
 * references with their subquery expressions.
 *
 * Only processes SQL that contains known formula column aliases — fast path
 * for all other queries (str_contains check before any heavy logic).
 *
 * @internal
 */
final class FormulaConnection extends AbstractConnectionMiddleware
{
    public function __construct(
        Connection $connection,
        private readonly FormulaRegistry $registry,
        private readonly string $rootAlias = 't0',
    ) {
        parent::__construct($connection);
    }

    public function prepare(string $sql): Statement
    {
        return parent::prepare($this->process($sql));
    }

    public function query(string $sql): Result
    {
        return parent::query($this->process($sql));
    }

    public function exec(string $sql): int
    {
        return parent::exec($this->process($sql));
    }

    /**
     * Replaces "t0.alias" references with formula subquery
     * expressions for SQL generated by BasicEntityPersister.
     *
     * Fast path: if no formula alias is found in the SQL — returns unchanged.
     * This avoids any overhead for queries unrelated to formula entities.
     */
    private function process(string $sql): string
    {
        // Quick check: does this SQL come from BasicEntityPersister?
        // It always starts with SELECT and contains "FROM ... t0"
        if (!str_contains($sql, " $this->rootAlias.")) {
            return $sql;
        }

        // Collect all formula metadata indexed by alias
        $formulasByAlias = $this->collectFormulasByAlias($sql);

        foreach ($formulasByAlias as $alias => $meta) {
            $columnRef ="$this->rootAlias.$alias";

            if (!str_contains($sql, $columnRef)) {
                continue;
            }

            $sql = str_replace($columnRef, $this->resolvePlaceholder($meta->sql), $sql);
        }

        return $sql;
    }

    /**
     * Replaces the {this} placeholder with the actual SQL table alias.
     */
    private function resolvePlaceholder(string $sql): string
    {
        return str_replace('{this}', $this->rootAlias, $sql);
    }

    /**
     * Scans all registered formula metadata and returns those whose alias
     * appears in the given SQL string.
     *
     * We iterate over scanned classes in the registry to find relevant formulas.
     *
     * @return array<string, FormulaMetadata>
     */
    private function collectFormulasByAlias(string $sql): array
    {
        $result = [];

        foreach ($this->registry->getScannedClasses() as $className) {
            foreach ($this->registry->getForClass($className) as $meta) {
                if (str_contains($sql, "$this->rootAlias.$meta->alias")) {
                    $result[$meta->alias] = $meta;
                }
            }
        }

        return $result;
    }
}
